export const metadata = {
    title: `Detail | Quran`,
    description: "Generated by create next app",
  };
  
  export default function DashboardLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
     <div>{children}</div>
    );
  }
  